import config
from Simulator.item_stats import uncraftable_items

CHAMPION_INFORMATION = 12
BOARD_SIZE = 28
BENCH_SIZE = 9
MAX_CHAMPION_IN_SET = 58
UNCRAFTABLE_ITEM = len(uncraftable_items)
MAX_BENCH_SPACE = 10
CHAMP_ENCODING_SIZE = 26

NUM_PLAYERS = config.NUM_PLAYERS
LOG_COMBAT = config.LOG_COMBAT

PRINTMESSAGES = True
LOGMESSAGES = True
MANA_DAMAGE_GAIN = 0.06
MAX_MANA_FROM_DAMAGE = 42.5

MOVEMENTDELAY = 550
STARMULTIPLIER = 1.8

ATTACK_PASSIVES = ["vayne", "jhin", "kalista", "warwick", "zed"]

MANA_PER_ATTACK = 10

BURN_SECONDS = 10
BURN_DMG_PER_SLICE = 0.025
BURN_HEALING_REDUCE = 0.5

# unit name
CHOSEN = None

GALIO_MULTIPLIER = 0.14
GALIO_TEAM_HEALTH_PERCENTAGE = 0.50

WARLORD_WINS = {"blue": 0, "red": 0}

LEAP_DELAY = 395  # assassins and shades

MATCHMAKING_WEIGHTS = 10
WEIGHTS_INCREMENT = 3

CRIT_CHANCE = 0
CRIT_DAMAGE = 1.5
SP = 1
