"""Single-step positioning environment.

When no replay queue is provided, battles are generated by PositionLevelingSystem.
"""

import numpy as np

from Simulator.simulators.tft_position_simulator import TFT_Position_Simulator


def main():
    env = TFT_Position_Simulator()
    observation, info = env.reset()
    mask = observation["action_mask"]
    legal = np.argwhere(mask > 0)
    action = np.zeros(env.max_action_count, dtype=np.int64)
    if len(legal):
        action[0] = legal[0][1]

    observation, reward, terminated, truncated, info = env.step(action)
    print("position env reward", reward, "terminated", terminated, "num_units", info.get("num_units"))
    env.close()


if __name__ == "__main__":
    main()
